openapi: 3.0.0
info:
  title: GitHub OAuth API
  description: API for handling GitHub OAuth authentication.
  version: 1.0.0
servers:
  - url: http://localhost:5000
    description: Local development server
paths:
  /auth/github:
    get:
      summary: Redirect users to GitHub login
      description: Redirects users to GitHub OAuth login page.
      responses:
        "302":
          description: Redirect to GitHub OAuth authorization URL
  /auth/github/token:
    get:
      summary: Exchange authorization code for access token
      description: Accepts the authorization code from the frontend, exchanges it for an access token, and returns the token to the frontend.
      parameters:
        - in: query
          name: code
          required: true
          schema:
            type: string
          description: The authorization code received from GitHub OAuth flow
      responses:
        "200":
          description: Successfully exchanged code for access token
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                    description: GitHub OAuth access token
        "400":
          description: No code provided
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "500":
          description: Failed to authenticate with GitHub
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
