name: CI Pipeline

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main
      - release

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Cache schema
      - name: Cache schema
        id: cache-schema
        uses: actions/cache@v4
        env: 
          cache-name: cache-schema-gql
        with:
          path: ./
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('./schema.graphql') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-
            ${{ runner.os }}-


      # Step 3: Get Resources
      - if: ${{ steps.cache-schema.outputs.cache-hit != 'true' }}
        name: Get resources
        run: |
          curl -o schema.graphql https://docs.github.com/public/fpt/schema.docs.graphql

      # Step 4: Build Docker image
      - name: Build Docker image
        run: docker build -t visfork-ci -f Dockerfile.build .

      # Step 5: Run Tests
      - name: Run tests
        run: docker run --rm visfork-ci npm run test-slim

      # Step 6: Build 
      - name: Build
        run: docker run --rm visfork-ci npm run build

      # Step 7: TODO: Store the build artifact
