name: CI Pipeline

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main
      - develop

jobs:
  setup:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get resources
        run: |
              curl -o schema.graphql https://docs.github.com/public/fpt/schema.docs.graphql
              curl https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/api.github.com.2022-11-28.yaml -L -o openapi-schema.yaml

      - name: Build Docker image
        run: docker build -t visfork-ci -f Dockerfile.build .

      - name: Run Docker container
        run: |
              if [ "$(docker ps -aq -f name=visfork-ci)" != "" ]; then
                docker stop visfork-ci
                docker rm visfork-ci
              fi
              docker run -dit --name visfork-ci \
                -e VITE_AUTH_URL=${{ secrets.AUTH_URL }} \
                -e VITE_API_URL=https://api.github.com/ \
                visfork-ci bash


  test-build-deploy:
    runs-on: self-hosted
    needs: setup

    steps:
      - name: Run ESLint
        run: docker exec visfork-ci npm run lint

      - name: Run tests
        run: docker exec visfork-ci npm run test

      # - name: Authentication
      #   if: github.ref == 'refs/heads/main'
      #   run: |
      #         docker cp ~/auth/.env visfork-ci:/workspace/.contrib
      #         docker cp ~/auth/backend/.env visfork-ci:/workspace/.contrib/backend
      #         docker cp ~/auth/backend/index.js visfork-ci:/workspace/.contrib/backend

      - name: Build
        run: docker exec visfork-ci npm run build

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: docker cp visfork-ci:/workspace/dist/. /var/www/html/react-app

  cleanup:
    runs-on: self-hosted
    needs: test-build-deploy

    steps:
      - name: Stop and Remove Docker Image
        run: |
              if [ "$(docker ps -aq -f name=visfork-ci)" = "" ]; then
                echo "visfork-ci container is not running"
              else
                docker stop visfork-ci
                docker rm visfork-ci
              fi
