name: CI Pipeline

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main
      - develop

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      # Step 1
      # Clone the repository to the CI runner
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2
      # Check cache for schema.graphql file. Use it if it exists, otherwise execute Step 3
      - name: Cache graphql schema
        # Variable used for referring to this step in subsequent steps
        id: cache-schema-gql
        uses: actions/cache@v4
        env: 
          cache-name: cache-schema-gql
        with:
          # Since the schema file should be located in the root directory of the project, we define this as the path
          path: ./
          # The key(s) used for finding back the cache once the cache has been generated
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('./schema.graphql') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-
            ${{ runner.os }}-


      # Step 3
      # If schema.graphql has not been cached before (or the cache has expired), it will download it again
      - if: ${{ steps.cache-schema-gql.outputs.cache-hit != 'true' }}
        name: Get resources
        run: |
          curl -o schema.graphql https://docs.github.com/public/fpt/schema.docs.graphql

      # Step 4: Cache openapi schema
      # Check cache for schema.graphql file. Use it if it exists, otherwise execute Step 3
      - name: Cache openapi schema
        # Variable used for referring to this step in subsequent steps
        id: cache-schema-openapi
        uses: actions/cache@v4
        env: 
          cache-name: cache-schema-openapi
        with:
          # Since the schema file should be located in the root directory of the project, we define this as the path
          path: ./
          # The key(s) used for finding back the cache once the cache has been generated
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('./openapi-schema.yaml') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-
            ${{ runner.os }}-


      # Step 5: Get openapi Resources
      # If openapi schema has not been cached before (or the cache has expired), it will download it again
      - if: ${{ steps.cache-schema-openapi.outputs.cache-hit != 'true' }}
        name: Get resources
        run: |
          curl https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/api.github.com.2022-11-28.yaml -L -o openapi-schema.yaml


      # Step 6: Build Docker image
      - name: Build Docker image
        run: docker build -t visfork-ci -f Dockerfile.build .
      
      # Run 7 inside a docker container for consistency
      - name: Run ESLint
        run: docker run --rm visfork-ci npm run lint

      # Step 8
      - name: Run tests
        run: docker run --rm visfork-ci npm run test 

      # Step 9
      - name: Build
        run: docker run --rm visfork-ci npm run build

      # Step 7
      # This is so we can use cached files to build faster next time
      # - name: Store Build Artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: build-output
      #     path: dist/

  # deploy:
  #   runs-on: ubuntu-latest

    # push the build artifact generated in build@step7 to the VM
    # NOTE: also either run a script on the server remotely as a step here,
    # or add a trigger to the server to automatically publish the new build
