name: CI Pipeline

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main
      - develop

jobs:
  setup:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set Up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Get resources
        run: |
              curl -o schema.graphql https://docs.github.com/public/fpt/schema.docs.graphql
              curl https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/api.github.com.2022-11-28.yaml -L -o openapi-schema.yaml
              cp /opt/simian/simian-4.0.0.jar .

      - name: Build Docker image
        run: docker build -t visfork-ci -f Dockerfile.build .

      - name: Run Docker container
        run: |
              if [ "$(docker ps -aq -f name=visfork-ci)" != "" ]; then
                docker stop visfork-ci
                docker rm visfork-ci
              fi
              docker run -dit --name visfork-ci \
                -e VITE_AUTH_URL=${{ secrets.AUTH_URL }} \
                -e VITE_API_URL=https://api.github.com \
                visfork-ci bash


  build-test-deploy:
    runs-on: self-hosted
    needs: setup

    steps:
      - name: Build
        run: docker exec visfork-ci npm run build

      - name: Run ESLint
        run: docker exec visfork-ci npm run lint

      - name: Run tests
        run: docker exec visfork-ci npm run test

      - name: Run Simian Analysis
        run: |
          chmod +x .contrib/Simian/simian.sh

          java -jar simian-4.0.0.jar \
            -includes=src/**.ts \
            -includes=src/**.tsx \
            -excludes=src/**test.ts \
            -excludes=test/**.ts \
            -excludes=src/**test.tsx \
            -excludes=test/**.tsx \
            -balanceParentheses+

          if grep -q "Found [1-9][0-9]* duplicate lines" simian.log; then
            echo "Duplicate code detected!"
            exit 1
          fi

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: docker cp visfork-ci:/workspace/dist/. /var/www/html/react-app

  cleanup:
    runs-on: self-hosted
    needs: build-test-deploy

    steps:
      - name: Stop and Remove Docker Image
        run: |
              if [ "$(docker ps -aq -f name=visfork-ci)" = "" ]; then
                echo "visfork-ci container is not running"
              else
                docker stop visfork-ci
                docker rm visfork-ci
              fi
