name: CI Pipeline

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main
      - develop

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      # Step 1
      # Clone the repository to the CI runner
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Build Docker image
      - name: Build Docker image
        run: docker build -t visfork-ci -f Dockerfile.build .

      # Step 3: Run tests
      - name: Run tests
        run: docker run --rm visfork-ci npm run test-slim # uses fast testing (see package.json -> scripts)

      # Step 4: Build
      - name: Build
        run: docker run --rm visfork-ci npm run build

      # Step 7:
      # This is so we can use cached files to build faster next time
      # - name: Store Build Artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: build-output
      #     path: dist/

  # deploy:
  #   runs-on: ubuntu-latest

    # push the build artifact generated in build@step7 to the VM
    # NOTE: also either run a script on the server remotely as a step here,
    # or add a trigger to the server to automatically publish the new build
