name: CI Pipeline

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main
      - develop

jobs:
  setup:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Get GraphQL resources
      - name: Get resources
        run: |
          curl -o schema.graphql https://docs.github.com/public/fpt/schema.docs.graphql

      # Get openapi Resources
      - name: Get resources
        run: |
          curl https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/api.github.com.2022-11-28.yaml -L -o openapi-schema.yaml

      # Step 6: Build Docker image
      - name: Remove existing Docker container if exists
        run: |
              if [ "$(docker ps -aq -f name=visfork)" != "" ]; then
                docker stop visfork
                docker rm visfork
              fi

      - name: Run Docker container
        run: docker run -dit --name visfork visfork-ci bash


  test-build-deploy:
    runs-on: self-hosted
    needs: setup

    steps:
      - name: Run ESLint
        run: docker exec visfork npm run lint

      - name: Run tests
        run: docker exec visfork npm run test 

      - name: Build
        run: docker exec visfork npm run build

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: docker cp visfork:/workspace/dist/. /var/www/html/react-app

  cleanup:
    runs-on: self-hosted
    needs: test-build-deploy

    steps:
      - name: Stop and Remove Docker Image
        run: |
              if [ "$(docker ps -aq -f name=visfork)" = "" ]; then
                echo "visfork container is not running"
              else
                docker stop visfork
                docker rm visfork
              fi
