name: CI Pipeline

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main
      - release

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Get Resources
      - name: Get Resources
        run: |
          curl -o schema.graphql https://docs.github.com/public/fpt/schema.docs.graphql

      # Step 3: Build Docker image
      - name: Build Docker image
        run: docker build -t visfork-ci -f Dockerfile.build .

      # Step 4: Run Tests
      - name: Run Tests
        run: docker run --rm visfork-ci npm run test-slim

      # Step 5: Build 
      - name: Build
        run: docker run --rm visfork-ci npm run build

      # Step 6: TODO: Store the build artifact
